# Generated by Django 5.1.7 on 2025-03-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_trip_logdetail_tripdetail'),
    ]

    operations = [
    migrations.RunSQL(
            sql="ALTER TABLE api_logdetail DROP CONSTRAINT api_logdetail_trip_id_key;",
            reverse_sql="ALTER TABLE api_logdetail ADD CONSTRAINT api_logdetail_trip_id_key UNIQUE (trip_id);", #This adds the constraint back, if the migration needs to be reversed.
        ),
            ]
