# Generated by Django 5.1.7 on 2025-03-30 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250330_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdetail',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_details', to='api.trip'),
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_book', to='api.logdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_datapoint', models.PositiveIntegerField(help_text='Represents 15-minute intervals in a 24-hour period (1-96).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(96)])),
                ('activity', models.CharField(choices=[('OFFDUTY', 'Off Duty'), ('DRIVING', 'Driving'), ('ONDUTY', 'On Duty'), ('SLEEPERBERTH', 'Sleeper Berth')], max_length=20)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.logbook')),
            ],
            options={
                'ordering': ['x_datapoint'],
            },
        ),
    ]
